{"componentChunkName":"component---src-templates-blog-post-js","path":"/trouble-shooting-moduleerror-ndef/","result":{"data":{"site":{"siteMetadata":{"title":"NARAZUKE","author":[{"name":"nozzle","summary":"who lives in gummaken.","social":{"github":"nozzlex3"}},{"name":"konnyaku","summary":"who is known as Siege Sukosuko Samurai.","social":{"github":"wabetarou"}}]}},"markdownRemark":{"id":"4f32cd38-425d-5c6f-ad9d-67808684ae86","excerpt":"経緯 ラズパイにパソリを繋いで NFC タッチ！ これを参考にしてラズパイにパソリを繋いで NFC タッチ！しようとしたのだが、 って打ったら、次のエラーが出た。 また、 って打ったら、次のエラーが出る 原因 よくわからない。python3.x 系で入手したパッケージを python2.x…","html":"<h2>経緯</h2>\n<p><a href=\"https://jellyware.jp/kurage/raspi/nfc.html\">ラズパイにパソリを繋いで NFC タッチ！</a></p>\n<p>これを参考にしてラズパイにパソリを繋いで NFC タッチ！しようとしたのだが、</p>\n<p><code class=\"language-text\">sudo python3 examples/tagtool.py show</code>って打ったら、次のエラーが出た。</p>\n<div class=\"gatsby-code-title\">bash</div>\n<div class=\"gatsby-highlight\" data-language=\"bash\"><pre class=\"language-bash\"><code class=\"language-bash\">Traceback <span class=\"token punctuation\">(</span>most recent call last<span class=\"token punctuation\">)</span>:\n  File <span class=\"token string\">\"tagtool.py\"</span>, line <span class=\"token number\">29</span>, <span class=\"token keyword\">in</span> <span class=\"token operator\">&lt;</span>module<span class=\"token operator\">></span>\n    <span class=\"token function\">import</span> ndef\nModuleNotFoundError: No module named <span class=\"token string\">'ndef'</span></code></pre></div>\n<p>また、</p>\n<p><code class=\"language-text\">sudo python examples/tagtool.py show</code>って打ったら、次のエラーが出る</p>\n<div class=\"gatsby-code-title\">bash</div>\n<div class=\"gatsby-highlight\" data-language=\"bash\"><pre class=\"language-bash\"><code class=\"language-bash\">Traceback <span class=\"token punctuation\">(</span>most recent call last<span class=\"token punctuation\">)</span>:\n  File <span class=\"token string\">\"tagtool.py\"</span>, line <span class=\"token number\">29</span>, <span class=\"token keyword\">in</span> <span class=\"token operator\">&lt;</span>module<span class=\"token operator\">></span>\n    <span class=\"token function\">import</span> cli\n  File <span class=\"token string\">\"/home/&amp;lt;user>/.../nfcpy/examples/cli.py\"</span>, line <span class=\"token number\">30</span>, <span class=\"token keyword\">in</span> <span class=\"token operator\">&amp;</span>lt<span class=\"token punctuation\">;</span>module<span class=\"token operator\">></span>\n    <span class=\"token function\">import</span> nfc\nModuleNotFoundError: No module named <span class=\"token string\">'nfc'</span></code></pre></div>\n<h2>原因</h2>\n<p>よくわからない。python3.x 系で入手したパッケージを python2.x 系で使おうとしているため、参照先を失って出るエラーかもしれない。</p>\n<p>pyenv で python3.x 系にしてても、sudo pip list だと python2.x の pip list が出るから、sudo python が python2.x 系で認識されちゃうのが良くないのでは？</p>\n<p>解決法\nラズパイにパソリを繋いで NFC タッチ！(<a href=\"https://jellyware.jp/kurage/raspi/nfc.html\">https://jellyware.jp/kurage/raspi/nfc.html</a>)</p>\n<p>の通り、/etc/udev/rules.d/nfcdev.rules を作るとエラーが無くなった。この工程は sudo を不要にするためのものだが、python がきちんと python3 になるようになったため、と考えて良いのだろうか。とりあえず解決した。</p>\n<p>(Reposted from nozzlog, Written on 2020-11-10)</p>","fields":{"slug":"/trouble-shooting-moduleerror-ndef/"},"frontmatter":{"title":"nfcpyの実験中\"ModuleNotFoundError No module named 'ndef'が出た","created":"2021-03-18T16:45","updated":"2021-03-18T19:53","description":"出た","tag":["raspberrypi","python","trouble-shooting"],"author":["nozzle"],"category":"tech"}},"previous":{"fields":{"slug":"/raspberrypi-setting-memo/"},"frontmatter":{"title":"ラズパイ環境設定メモ"}},"next":null,"relatedPosts":{"totalCount":8,"edges":[{"node":{"fields":{"slug":"/raspberrypi-setting-memo/"},"frontmatter":{"title":"ラズパイ環境設定メモ"}}},{"node":{"fields":{"slug":"/trouble-shooting-moduleerror-ndef/"},"frontmatter":{"title":"nfcpyの実験中\"ModuleNotFoundError No module named 'ndef'が出た"}}},{"node":{"fields":{"slug":"/raspberrypi-static-ipaddress/"},"frontmatter":{"title":"ラズパイのIPアドレスを固定する方法"}}},{"node":{"fields":{"slug":"/wordpress-setting/"},"frontmatter":{"title":"WordPress設定備忘録"}}},{"node":{"fields":{"slug":"/raspberrypi-ssd-boot/"},"frontmatter":{"title":"SDカードなしでRaspberry Pi 4B を SSDでUSB bootする"}}},{"node":{"fields":{"slug":"/raspberrypi-google-drive/"},"frontmatter":{"title":"ラズパイでGoogle Driveを使う"}}},{"node":{"fields":{"slug":"/trouble-shooting-EPERM-npm-install/"},"frontmatter":{"title":"トラブルシュート：npm installすると、\"Error EPERM operation not permitted, unlink ...\"が出る"}}},{"node":{"fields":{"slug":"/pyenv-venv-virtual-environment/"},"frontmatter":{"title":"pyenvとvenvで仮想環境構築 ラズパイ編"}}}]}},"pageContext":{"id":"4f32cd38-425d-5c6f-ad9d-67808684ae86","previousPostId":"6d4af5d1-a31a-5c81-a4f4-b6d0500ba6a0","nextPostId":null,"category":"tech","tagList":["raspberrypi","python","trouble-shooting"]}},"staticQueryHashes":["3284037645","500847697"]}